"""The execution contract, HARNESS.md §3 and §4.

A sim supplies three callables and this module does the rest: run every seed at
every sweep point plus the null model, grade the result against the
pre-committed refutation condition, and emit the four artifacts.

The sim grades itself. Humans may dispute the grade, not compute it (§3.3).
"""

from __future__ import annotations

import argparse
import json
import platform
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable

from .manifest import (
    canonical_json,
    is_pilot,
    load,
    sha256_of,
    sha256_of_file,
    sweep_points,
)

SUPPORTED = "SUPPORTED"
REFUTED = "REFUTED"
INCONCLUSIVE = "INCONCLUSIVE"
VERDICTS = (SUPPORTED, REFUTED, INCONCLUSIVE)


@dataclass
class Verdict:
    """A graded result. `reason` is mandatory — an unexplained grade is not one."""
    verdict: str
    reason: str
    details: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.verdict not in VERDICTS:
            raise ValueError(f"verdict must be one of {VERDICTS}, got {self.verdict!r}")
        if not self.reason:
            raise ValueError("a verdict without a reason is not a verdict")


# A measurement: (seed, sweep_point, config) -> flat dict of numbers
MeasureFn = Callable[[int, dict[str, Any], dict[str, Any]], dict[str, float]]
# A grader: (observations, null_observations, config) -> Verdict
GradeFn = Callable[[list[dict[str, Any]], list[dict[str, Any]], dict[str, Any]], Verdict]


def _observations(fn: MeasureFn, config: dict[str, Any], points: list[dict[str, Any]],
                  label: str, quiet: bool) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    total = len(config["seeds"]) * len(points)
    done = 0
    for point in points:
        for seed in config["seeds"]:
            started = time.time()
            metrics = fn(seed, point, config)
            done += 1
            if not quiet:
                point_desc = ", ".join(f"{k}={v}" for k, v in point.items())
                print(f"  [{label} {done}/{total}] seed={seed} {point_desc} "
                      f"({time.time() - started:.1f}s)", file=sys.stderr, flush=True)
            rows.append({"seed": seed, "sweep": point, "metrics": metrics})
    return rows


def _summary_md(config: dict[str, Any], verdict: Verdict, obs: list[dict[str, Any]],
                null_obs: list[dict[str, Any]], elapsed: float, pilot: bool) -> str:
    lines = [
        f"# {config['name']} — {verdict.verdict}",
        "",
        f"Run: {time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())} · "
        f"{elapsed:.1f}s · {len(config['seeds'])} seeds × {len(sweep_points(config['sweeps']))} "
        f"sweep points" + ("  \n**PILOT** — fewer than 5 seeds (§2)" if pilot else ""),
        "",
        "## Claim",
        "",
        config.get("claim", "(no `claim` field in config.json)"),
        "",
        "## Pre-committed refutation condition",
        "",
        f"> {config['refute_if']}",
        "",
        "## Verdict",
        "",
        f"**{verdict.verdict}** — {verdict.reason}",
        "",
    ]
    if verdict.details:
        lines += ["## Detail", "", "```json",
                  json.dumps(verdict.details, indent=2, sort_keys=True), "```", ""]

    keys = sorted({k for row in obs for k in row["metrics"]})
    if keys:
        lines += ["## Measurements", "",
                  "| seed | " + " | ".join(list(obs[0]["sweep"]) + keys) + " |",
                  "|" + "---|" * (1 + len(obs[0]["sweep"]) + len(keys))]
        for row in obs:
            cells = [str(row["sweep"][k]) for k in obs[0]["sweep"]]
            cells += [f"{row['metrics'].get(k, float('nan')):.4f}" for k in keys]
            lines.append(f"| {row['seed']} | " + " | ".join(cells) + " |")
        lines.append("")

    null_keys = sorted({k for row in null_obs for k in row["metrics"]})
    if null_obs and null_keys:
        lines += [f"## Null model — `{config['null_model']}`", "",
                  "| seed | " + " | ".join(list(null_obs[0]["sweep"]) + null_keys) + " |",
                  "|" + "---|" * (1 + len(null_obs[0]["sweep"]) + len(null_keys))]
        for row in null_obs:
            cells = [str(row["sweep"][k]) for k in null_obs[0]["sweep"]]
            cells += [f"{row['metrics'].get(k, float('nan')):.4f}" for k in null_keys]
            lines.append(f"| {row['seed']} | " + " | ".join(cells) + " |")
        lines.append("")

    lines += ["---", "", "Generated by `sims/harness`. Do not edit — rerun instead."]
    return "\n".join(lines)


def run(config_path: str | Path, measure: MeasureFn, null: MeasureFn,
        grade: GradeFn, argv: list[str] | None = None) -> Verdict:
    """Execute the full contract and write results/<timestamp>/."""
    parser = argparse.ArgumentParser(description="Run a harness-conforming sim.")
    parser.add_argument("--config", default=str(config_path))
    parser.add_argument("--seeds", type=int, nargs="+", help="override config seeds")
    parser.add_argument("--results-dir", help="override results/ location")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args(argv)

    config = load(args.config)
    if args.seeds:
        config["seeds"] = args.seeds
    pilot = is_pilot(config)
    points = sweep_points(config["sweeps"])

    started = time.time()
    if not args.quiet:
        print(f"{config['name']}: {len(config['seeds'])} seeds × {len(points)} sweep "
              f"points (+ null), est. {config['runtime_estimate_s']}s",
              file=sys.stderr, flush=True)

    obs = _observations(measure, config, points, "measure", args.quiet)
    null_obs = _observations(null, config, points, "null", args.quiet)
    verdict = grade(obs, null_obs, config)
    elapsed = time.time() - started

    stamp = time.strftime("%Y-%m-%dT%H%MZ", time.gmtime())
    root = Path(args.results_dir or (Path(args.config).parent / "results" / stamp))
    root.mkdir(parents=True, exist_ok=True)

    metrics = {
        "name": config["name"],
        "run_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "elapsed_s": round(elapsed, 3),
        "pilot": pilot,
        "seeds": config["seeds"],
        "sweeps": config["sweeps"],
        "null_model": config["null_model"],
        "observations": obs,
        "null_observations": null_obs,
        "verdict": verdict.verdict,
        "reason": verdict.reason,
        "details": verdict.details,
        "environment": {
            "python": platform.python_version(),
            "platform": platform.platform(),
        },
    }
    metrics_path = root / "metrics.json"
    metrics_path.write_text(json.dumps(metrics, indent=2, sort_keys=True) + "\n",
                            encoding="utf-8")

    (root / "summary.md").write_text(
        _summary_md(config, verdict, obs, null_obs, elapsed, pilot) + "\n",
        encoding="utf-8")

    # §3.4 — the ledger entry. MEASURE, because the sim was run against a
    # refutation condition committed to git before any data existed. A run whose
    # refute_if was edited after seeing data must be marked EXPLORATORY (§4).
    entry = {
        "type": "EXPLORATORY" if config.get("exploratory") else "MEASURE",
        "name": config["name"],
        "claim": config.get("claim", ""),
        "refute_if": config["refute_if"],
        "null_model": config["null_model"],
        "verdict": verdict.verdict,
        "reason": verdict.reason,
        "metrics_hash": sha256_of_file(metrics_path),
        "config_hash": sha256_of(config),
        "seeds": len(config["seeds"]),
        "pilot": pilot,
        "run_at": metrics["run_at"],
        "results_dir": str(root),
    }
    (root / "ledger_entry.jsonl").write_text(canonical_json(entry) + "\n",
                                             encoding="utf-8")

    if not args.quiet:
        print(f"\n{verdict.verdict}: {verdict.reason}", file=sys.stderr)
        print(f"artifacts: {root}", file=sys.stderr)
    return verdict


# --------------------------------------------------------------------------
# Grading helpers — §4 verdict discipline
# --------------------------------------------------------------------------

def by_sweep(rows: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    """Group observation rows by a stable string key for their sweep point."""
    grouped: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        grouped.setdefault(canonical_json(row["sweep"]), []).append(row)
    return grouped


def count_where(rows: list[dict[str, Any]], predicate: Callable[[dict[str, float]], bool]) -> int:
    return sum(1 for row in rows if predicate(row["metrics"]))
